#!/bin/bash

cd restify/
npm install restify
cd ..

node restify/app.js &

sleep 1
./generate-lot-of-data
curl --no-buffer --proxy "" -X GET http://127.0.0.1:8080/ --data-binary @./data.txt
sleep 1

killall node
